export { default as SettingsPage } from './pages/SettingsPage'
export { default as SuperAdminSettingsPage } from './pages/SuperAdminSettingsPage'
export { default as SalesExecutiveSettingsPage } from './pages/SalesExecutiveSettingsPage'
export { default as ClinicAdminSettingsPage } from './pages/ClinicAdminSettingsPage'
export { default as PractitionerSettingsPage } from './pages/PractitionerSettingsPage'
export { default as PatientPortalSettingsPage } from './pages/PatientPortalSettingsPage'
export { default as AdminProfilePage } from './pages/AdminProfilePage'
export { default as AdminPage } from './pages/AdminPage'
export { default as BranchPage } from './pages/BranchPage'
export { default as DoctorsManagePage } from './pages/DoctorsManagePage'
export { default as SubscriptionPage } from './pages/SubscriptionPage'
export { default as AiNotePage } from './pages/AiNotePage'
export { default as TenantPage } from './pages/TenantPage'
export { default as PaymentTermsPage } from './pages/PaymentTermsPage'
export { default as TemplateManagePage } from './pages/TemplateManagePage'
export { default as ClinicDetailsPage } from './pages/ClinicDetailsPage'

